<div class="dropdown-wrap">
    <button class="dropdown-button">
        <span><?= $block->escapeHtml(__('Dropdown open button')) ?></span>
    </button>
    <div id="dropdown-dialog" data-role="dropdownDialog">
        <?= $block->escapeHtml(__('Dropdown content')) ?>
    </div>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'dropdownDialog'
        ], function($, dropdownDialog) {
            'use strict';

            $('#dropdown-dialog').dropdownDialog({
                appendTo: '.dropdown-wrap',
                triggerTarget: '.dropdown-button',
                closeOnMouseLeave: false,
                closeOnEscape: true,
                timeout: 2000,
                triggerClass: 'active',
                parentClass: 'active',
                buttons: [{
                    text: $.mage.__('Close'),
                    click: function () {
                        $(this).dropdownDialog("close");
                    }
                }]
            });
        }
    );
</script>
